name: Merge Rules and Publish

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  merge-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}  # 使用 PAT 检出代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python merge_rules.py

      - name: Check if all.txt exists
        run: ls -l

      - name: Clean up __pycache__
        run: rm -rf __pycache__

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git rm -f __pycache__/config.cpython-312.pyc || true
          git add all.txt
          git commit -m "Update all.txt - $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git main